<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Barang extends Model
{
    protected $table = 'barang';
    protected $primaryKey = 'id_barang';
    public $incrementing = false;
    protected $keyType = 'string';
    public $timestamps = false;

    protected $fillable = ['nama', 'harga'];

    // id_barang is auto-generated by the DB trigger, so we never fill it
    protected static function booted(): void
    {
        // When inserting, we need to send a placeholder so the trigger fires.
        // We pass an empty string; the trigger will overwrite it.
        static::creating(function ($model) {
            if (empty($model->id_barang)) {
                $model->id_barang = '';
            }
        });
    }
}
